name = "notes-server-components"
compatibility_date = "2022-05-10"

[durable_objects]
bindings = [
  { name = "DO", class_name = "NotesDB" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["NotesDB"] # Array of new classes
